# Generated by Django 5.1.7 on 2025-06-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='newsletter',
            constraint=models.UniqueConstraint(fields=('full_name', 'email'), name='unique name/email'),
        ),
    ]
