# Generated by Django 5.0.6 on 2024-07-14 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_rating_alter_product_strength'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='strength',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
