# Generated by Django 5.0.6 on 2025-02-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_size_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_strength',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
