# Generated by Django 5.0.6 on 2025-02-22 00:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_has_strength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AddField(
            model_name='product',
            name='sku1',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'kilogram'), ('g', 'gram'), ('L', 'liter'), ('mL', 'milliliter'), ('', 'no_unit')], default='', max_length=2),
        ),
    ]
