# Generated by Django 5.0.6 on 2025-02-23 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_sku1_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='strength',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
